# Generated by Django 5.2.8 on 2026-01-28 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StudySession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(help_text='Çalışma yapılan dersin adı', max_length=200, verbose_name='Ders Adı')),
                ('duration', models.IntegerField(help_text='Çalışma süresi dakika cinsinden', verbose_name='Süre (Dakika)')),
                ('date', models.DateField(help_text='Çalışma oturumunun yapıldığı tarih', verbose_name='Tarih')),
                ('category', models.CharField(help_text='Çalışma türü kategorisi', max_length=100, verbose_name='Kategori')),
                ('note', models.TextField(blank=True, help_text='Çalışma hakkında ek notlar (isteğe bağlı)', null=True, verbose_name='Not')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Kaydın oluşturulduğu tarih ve saat', verbose_name='Oluşturulma Zamanı')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Kaydın son güncellendiği tarih ve saat', verbose_name='Güncellenme Zamanı')),
            ],
            options={
                'verbose_name': 'Çalışma Oturumu',
                'verbose_name_plural': 'Çalışma Oturumları',
                'ordering': ['-date', '-created_at'],
            },
        ),
    ]
