# Generated by Django 5.2.8 on 2026-01-29 07:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0003_alter_studysession_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studysession',
            name='category',
        ),
    ]
