# Generated by Django 5.2.8 on 2026-01-29 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0004_remove_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studysession',
            name='subject',
            field=models.CharField(help_text='Çalışma yapılan dersin adı', max_length=125, verbose_name='Ders Adı'),
        ),
    ]
