# Generated by Django 5.2.8 on 2026-02-02 09:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0005_change_subject_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TodoItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Görevin başlığı', max_length=200, verbose_name='Başlık')),
                ('description', models.TextField(blank=True, help_text='Görev hakkında detaylı açıklama (isteğe bağlı)', null=True, verbose_name='Açıklama')),
                ('completed', models.BooleanField(default=False, help_text='Görevin tamamlanma durumu', verbose_name='Tamamlandı')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Görevin oluşturulduğu tarih ve saat', verbose_name='Oluşturulma Zamanı')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Görevin son güncellendiği tarih ve saat', verbose_name='Güncellenme Zamanı')),
                ('user', models.ForeignKey(help_text='Görevin sahibi kullanıcı', on_delete=django.db.models.deletion.CASCADE, related_name='todo_items', to=settings.AUTH_USER_MODEL, verbose_name='Kullanıcı')),
            ],
            options={
                'verbose_name': 'Yapılacaklar Öğesi',
                'verbose_name_plural': 'Yapılacaklar Öğeleri',
                'ordering': ['-created_at'],
            },
        ),
    ]
