# Generated by Django 5.2.8 on 2026-02-02 09:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0006_todoitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todoitem',
            name='description',
        ),
    ]
