# Generated by Django 5.2.8 on 2026-02-02 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0007_remove_todoitem_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todoitem',
            name='title',
            field=models.CharField(help_text='Görevin başlığı', max_length=60, verbose_name='Başlık'),
        ),
    ]
