# Generated by Django 5.2.8 on 2026-02-02 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0008_alter_todoitem_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todoitem',
            name='title',
            field=models.CharField(help_text='Görevin başlığı', max_length=80, verbose_name='Başlık'),
        ),
    ]
