# Generated by Django 5.2.8 on 2026-02-03 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0009_alter_todoitem_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='todoitem',
            name='is_edited',
            field=models.BooleanField(default=False, help_text='Görevin başlığının düzenlenip düzenlenmediği', verbose_name='Düzenlendi'),
        ),
    ]
