# Generated by Django 5.2.8 on 2026-02-03 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0010_todoitem_is_edited'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todoitem',
            name='title',
            field=models.CharField(help_text='Görevin başlığı', max_length=100, verbose_name='Başlık'),
        ),
    ]
