# Generated by Django 5.2.8 on 2026-02-03 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0011_alter_todoitem_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='todoitem',
            name='important_marked_at',
            field=models.DateTimeField(blank=True, help_text='Görevin önemli olarak işaretlendiği tarih ve saat', null=True, verbose_name='Önemli İşaretlenme Zamanı'),
        ),
        migrations.AddField(
            model_name='todoitem',
            name='is_important',
            field=models.BooleanField(default=False, help_text='Görevin önemli olup olmadığı', verbose_name='Önemli'),
        ),
    ]
