# Generated by Django 5.2.8 on 2026-02-22 20:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0012_todoitem_important_marked_at_todoitem_is_important'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CalendarEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Tarih')),
                ('title', models.CharField(max_length=100, verbose_name='Başlık')),
                ('color', models.CharField(choices=[('#667eea', 'Mor'), ('#f5576c', 'Pembe'), ('#4ecdc4', 'Turkuaz'), ('#45b7d1', 'Mavi'), ('#96ceb4', 'Yeşil'), ('#ffeaa7', 'Sarı'), ('#dfe6e9', 'Gri')], default='#667eea', max_length=7, verbose_name='Renk')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calendar_events', to=settings.AUTH_USER_MODEL, verbose_name='Kullanıcı')),
            ],
            options={
                'verbose_name': 'Takvim Etkinliği',
                'verbose_name_plural': 'Takvim Etkinlikleri',
                'ordering': ['date', 'created_at'],
            },
        ),
    ]
