# Generated by Django 5.2.8 on 2026-03-05 16:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0013_calendar_event'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='calendarevent',
            name='color',
            field=models.CharField(choices=[('#c9a0ff', 'Mor'), ('#8fc4ff', 'Koyu Mavi'), ('#88eeff', 'Açık Turkuaz'), ('#f5b0e6', 'Pembe'), ('#b8e8a8', 'Yeşil'), ('#fff0b8', 'Sarı'), ('#ffcc99', 'Turuncu'), ('#f5a0a0', 'Pastel Kırmızı')], default='#c9a0ff', max_length=7, verbose_name='Renk'),
        ),
        migrations.CreateModel(
            name='UserStudyGoal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weekly_goal_minutes', models.PositiveIntegerField(default=420, help_text='Haftada hedeflenen toplam çalışma süresi (dakika)', verbose_name='Haftalık hedef (dakika)')),
                ('monthly_goal_minutes', models.PositiveIntegerField(default=1800, help_text='Ayda hedeflenen toplam çalışma süresi (dakika)', verbose_name='Aylık hedef (dakika)')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='study_goal', to=settings.AUTH_USER_MODEL, verbose_name='Kullanıcı')),
            ],
            options={
                'verbose_name': 'Çalışma Hedefi',
                'verbose_name_plural': 'Çalışma Hedefleri',
            },
        ),
    ]
